development:
  adapter: postgresql
  encoding: unicode
  database: mastercontrol 
  pool: 5
  username: master1
  password: harper123

test:
  adapter: postgresql
  encoding: unicode
  database: mastercontrol
  pool: 5
  username: master1
  password: harper123

production:
  adapter: postgresql
  encoding: unicode
  database: mastercontrol
  pool: 5
  username: master1
  password: harper123
